{% set data= load_setup_py_data() %}
package:
  name: "ts-phosim"
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script: python -m pip install --no-deps --ignore-installed .

test:
  requires:
    - ts-conda-build =0.3
    - rubin-env
  source_files:
    - python
    - tests
    - setup.cfg
    - policy
  commands:
    - py.test -vs

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python
    - setuptools
    - setuptools_scm
    - rubin-env
